params:
  num_epochs: 80
  batch_size: 16
  lr: 1.0e-6
  early_stop_threshold: 30
  scheduler: constant       # constant, linear
  warmup_steps: 0
  model_head: none       # none, multilabel

paths:
  train_data: "/home/jovyan/shared-scratch/jhoon/CATBERT/data/train_300k_s2ef_is2re.pkl"
  val_data:  '/home/jovyan/shared-scratch/jhoon/CATBERT/is2re/val_2nd/val_10k.pkl'
  roberta_config: "roberta-base"
  tknz: "roberta-base"